
((DOCUMENT :ID "snr-in-dsb-am" :NAME "snr in dsb-am" :LINE 0)
 ((TITLE :LINE 2) "SNR in DSB-AM")
 ((DOCINFO :LINE 5)
  ((AUTHOR :LINE 5) ((PARAGRAPH :LINE 5) "Dr. John A.R. Williams"))
  ((FIELD :LINE 6) ((FIELD-NAME :LINE 6) "authorids")
   ((FIELD-BODY :LINE 6) ((PARAGRAPH :LINE 6) "willijar")))
  ((DATE :LINE 7) ((PARAGRAPH :LINE 7) "2001/04/05 08:19:19.734 GMT+1"))
  ((FIELD :LINE 8) ((FIELD-NAME :LINE 8) "summary")
   ((FIELD-BODY :LINE 8)
    ((PARAGRAPH :LINE 10)
     "On completing this section you should be able to calculate the effect on the signal to noise ratio of DSB-AM with synchronous detection")))
  ((FIELD :LINE 11) ((FIELD-NAME :LINE 11) "outcomes")
   ((FIELD-BODY :LINE 11)
    ((FIELD-LIST :LINE 14)
     ((FIELD :LINE 14)
      ((FIELD-NAME :LINE 14) " "
       ((PROBLEMATIC :ID "id3" :REFID "id2" :LINE -1)
        "Noise in Continuous-Wave Systems"))
      ((FIELD-BODY :LINE 14) ((PARAGRAPH :LINE 16) "1/2")))))))
 ((DECORATION :LINE -1)
  ((FOOTER :LINE -1)
   ((PARAGRAPH :LINE -1) "Generated on : Fri, 08 Sep 2006 10:24:48 +00 .
"
    "Generated by cl-docutils 0.0.1 from "
    ((REFERENCE :REFURI "http://docutils.sourceforge.net/rst.html" :LINE -1)
     "restructured text")
    " source.
")))
 ((PARAGRAPH :LINE 15) "We wish to compare  "
  ((EQUATION :LINE 16) "$\\mbox{SNR}_o$") " with  "
  ((EQUATION :LINE 16) "$\\mbox{SNR}_i$") " . It is common to define a  "
  ((EMPHASIS :LINE 15) "figure-of-merit")
  " for noise performance as the ratio  "
  ((EQUATION :LINE 16) "$\\mbox{SNR}_o/\\mbox{SNR}_i$")
  " . Care must be taken as there are several different measures of  "
  ((EQUATION :LINE 16) "$\\mbox{SNR}_i$") " .")
 ((FIGURE :LINE 20)
  ((IMAGE :WIDTH (70 . :%) :ALT
    "Adaptive Prediction with backward estimation (APB)" :LINE 20)
   "/home/willijar/dev/lisp/src/docutils/tests/adaptive-prediction-be.eps")
  ((CAPTION :LINE 20) "Adaptive Prediction with backward estimation (APB)"))
 ((SECTION :LINE -1) ((TITLE :LINE -1) "Docutils System Messages")
  ((SYSTEM-MESSAGE :ID "id2" :LEVEL :ERROR :LINE 14)
   ((PARAGRAPH :LINE -1)
    "Unknown target name \"noise in continuous-wave systems\""))))